#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=10

start_service() {
	config_load cpemonitor
	local enabled
	config_get_bool enabled main enabled 1
	[ "$enabled" = 1 ] || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/cpemonitord
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param term_timeout 20
	procd_set_param limits nofile="1024 1024"
	procd_close_instance
}

reload_service() {
	stop
	start
}

stop_service() {
	/usr/sbin/cpemonitor-quota cleanup >/dev/null 2>&1
}

service_triggers() {
	procd_add_reload_trigger cpemonitor
}
